### ISSUE TITLE
Assigned New Mission on Exit Campaign Summary

### ISSUE THREAD

**Issue by FirebarSim** [Dot-M134/ColdWaters-DotMod#1]
After doing a spec ops mission, I got assigned the task to return to port. I pause, save, and then check out the summary menu (to see my campaign progress) 

As soon as I did that, I was assigned a new mission (instead of the usual, which is being assigned one upon return to port). Not sure how 'reproducible' this is, but figured I'd identify it anyway?

https://discord.com/channels/824084038394445824/866120539512373268/869135986884501565

**Comment by Lazarus0909** [comment]
From user - Yeah and sorry, just to add to this today - Soviet 1984 campaign. Was on the 'return to murmansk' mission after doing a spec ops dropoff, believe i was reassigned to either sink the tenders or stopping a landing party. (it was 100% a convoy sinking mission).
(reassigned immediately after checking the summary option in the pause menu)

**Comment by Dot-M134** [comment]
This issue originates from original game. If current mission is "Return to base" then a mission check applied after exiting statistics. Sometimes for some reason player is able to gain another mission this way. Why does this happen is unclear to me.
I've made some changes and I belive this issue is fixed, but due to its unstable nature additional feedback is needed.
